### ISSUE TITLE
@babel/parser 7.5.0 isn't published

### ISSUE THREAD

**Issue by alubbe** [babel/babel#10163]
## Bug Report

**Current Behavior**
@babel/traverse 7.5.0 wants @babel/parser ^7.5.0 but nothing matches that

Could you please publish @babel/parser 7.5.0?

**Comment by nicolo-ribaudo** [comment]
I accidentally published it as "next" instead of "latest". It should be fixed now.

**Comment by vincentholmen** [comment]
Hello @nicolo-ribaudo,

Unfortunately, I am still encountering this behavior and unable to install babel/parser 7.5.0, which is causing issues within CI Pipeline.

Can you confirm this has been corrected and the latest version 7.5.0 is available?

**Comment by LuisEGR** [comment]
I am also having problems when installing this:

```
npm install  @babel/generator@^7.5.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/generator@^7.5.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
I can see the v7.5.0 on https://www.npmjs.com/package/@babel/generator but when I install with the default command I get the 7.4.4:

```
npm i @babel/generator
+ @babel/generator@7.4.4
updated 1 package in 0.8s
```
Can anyone correct the package on npm please?

**Comment by Jrfidellis** [comment]
Maybe related with #10164?

**Comment by nicolo-ribaudo** [comment]
`@babel/generator` was correctly published: https://www.npmjs.com/package/@babel/generator

Please try running the workarounds described at https://github.com/babel/babel/issues/10165
