### ISSUE TITLE
hello world example at http://babeljs.io/

### ISSUE THREAD

**Issue by djindjic** [babel/babel#1073]
I am trying to find which files I need to include in my js web app transpiled with babel and I cant find it at babel's home page. Just simple index.html with app-compiled.js without any package manager or anything. First link in menu is "learn es6", second is list of plugins for different environment, but third link looks very confusing for me and maybe for others. Here is a (unsorted?) list of terms in which I cant understand a difference between polyfill and runtime. Is core-js part of babel polyfill or it is a part of runtime with regenerator? After reading this:
>Available from the browser-polyfill.js file within the babel directory of an npm release.

I have tried to include ./node_modules/babel/browser-polyfill.js into my index.html but it still doesn't work. I am getting this errror: "Uncaught ReferenceError: _core is not defined".

Could you help me or add some hello world examples on home page? :)

edit:
just to add, what is a difference between this to npm packages:
https://www.npmjs.com/package/babel-runtime
https://www.npmjs.com/package/babel
?

Thanks!

**Comment by hzoo** [comment]
Maybe checking out https://babeljs.io/docs/usage/cli/ will help? You can run it from the command line to generate the compiled code and just use that in your index.html? If it's already compiled you won't need an extra files.

```html
<script src="app-compiled.js></script>
```
Or are you trying to include the source file (not compiled) in index.html?

**Comment by sebmck** [comment]
@djindjic See the docs on the [runtime](http://babeljs.io/docs/usage/runtime). Don't enable the runtime unless you're in a CommonJS environment, that should fix the `_core is undefined` error.

**Comment by djindjic** [comment]
thanks @sebmck. I am using babel over jspm and everything works perfect! I've just wanted to try it alone and still cant make id work. Ok I understood that I cant use runtime without commonjs environment, but then I have tried to use browser-polifill.js.
Does this need to work:
```html
<!doctype html>
<html>
  <head>
  </head>
  <body>
    <script src="node_modules/babel/browser-polyfill.js"></script>
    <script>
    class Test {
      hello() {
        console.log('hello');
      }
    }
    let test = new Test();
    test.hello();
    </script>
  </body>
</html>
```

**Comment by sebmck** [comment]
As the [browser docs](http://babeljs.io/docs/usage/browser/) say you need to add the attribute `type="text/babel"`.

**Comment by djindjic** [comment]
ah sorry. I have added type attribute, and browser.js as it is written in browser docs (but what is a browser-polyfill.js?) and getting this errror:
![image](https://cloud.githubusercontent.com/assets/1564068/6820300/d95087cc-d2cd-11e4-8efd-242df77d09a4.png)

**Comment by sebmck** [comment]
Try changing:

```html
<script src="node_modules/babel/browser-polyfill.js"></script>
```

to

```html
<script charset="utf-8" src="node_modules/babel/browser-polyfill.js"></script>
```

**Comment by djindjic** [comment]
no :( I have make example at jsbin
http://jsbin.com/lozururuze/edit?html,console,output

**Comment by djindjic** [comment]
btw what is a difference between browser-polifill and browser.js?

**Comment by sebmck** [comment]
Whoops, meant `browser.js` not `browser-polyfill.js`. The `browser-polyfill.js` is a standalone build of the polyfill as dictated in the [polyfill docs](http://babeljs.io/docs/usage/polyfill/) and `browser.js` is the browser compiler as detailed in the [browser docs](http://babeljs.io/docs/usage/browser/).

**Comment by djindjic** [comment]
thanks, it works now and I understand. only one thing is not clear to me. If I want to use es6 precompiled to es5 with babel in browser without commonjs environment, I have to include browser-polyfill.js insted of browser.js and as I understand, browser-polyfill will allow me to use (ex.) _createClass as global function. So I have expected that this should work (?):
```html
<!doctype html>
<html>
  <head>
  </head>
  <body>
    <script charset="utf-8" src="node_modules/babel/browser-polyfill.js"></script>
    <script type="text/javascript">
    var Test = (function () {
      function Test() {
        _classCallCheck(this, Test);
      }

      _createClass(Test, {
        hello: {
          value: function hello() {
            console.log("hello");
          }
        }
      });

      return Test;
    })();

    var app__test = new Test();
    app__test.hello();
    </script>
  </body>
</html>
```
I'm getting:
>Uncaught ReferenceError: _createClass is not defined

**Comment by buzinas** [comment]
can anybody answer the djindjic's question above, please?

**Comment by eventualbuddha** [comment]
@buzinas @djindjic you're probably better off asking in the [Slack channel](https://babel-slack.herokuapp.com).
