### ISSUE TITLE
Regression in preset-react 7.9.x. 

### ISSUE THREAD

**Issue by andy128k** [babel/babel#11305]
## Bug Report

- [ ] I would like to work on a fix!

**Current Behavior**

After upgrade @babel/preset-react from 7.8.x to 7.9.x all tests in my project are failing with message:

```
Error: ProgressBar(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
```

After bisecting babel I have found a commit which breaks my project. https://github.com/babel/babel/commit/748897be0772d3569c92c26e061ba05ac26563b4

Those lines https://github.com/babel/babel/pull/11154/files#diff-8c3c9c6362e23bd456da3fb129f49a57L10-R12 gave me a clue how to workaround it. So, I added 
`{pragma: "React.createElement"}` and it helped. 

**Babel Configuration (babel.config.js, .babelrc, package.json#babel, cli command, .eslintrc)**
- Filename: `babel.config.js` Original

```js
module.exports = function(api) {
  const isTest = api.env('test');

  const envOptions = isTest
    ? {
      "targets": {
        "node": "current"
      }
    }
    : {
      modules: false,
      useBuiltIns: 'usage',
      corejs: 3,
      // debug: true,
    };

  return {
    "presets": [
      ["@babel/preset-env", envOptions],
      "@babel/preset-react"
    ],
    "plugins": [
      "@babel/plugin-proposal-class-properties"
    ],
  };
};
```

- Filename: `babel.config.js`  With workaround

```js
module.exports = function(api) {
  const isTest = api.env('test');

  const envOptions = isTest
    ? {
      "targets": {
        "node": "current"
      }
    }
    : {
      modules: false,
      useBuiltIns: 'usage',
      corejs: 3,
      // debug: true,
    };

  return {
    "presets": [
      ["@babel/preset-env", envOptions],
      ["@babel/preset-react", {
        pragma: "React.createElement",
      }],
    ],
    "plugins": [
      "@babel/plugin-proposal-class-properties"
    ],
  };
};
```

**Environment**

```
  System:
    OS: Linux 5.4 Debian GNU/Linux bullseye/sid
  Binaries:
    Node: 12.16.1 - ~/apps/nodejs/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - ~/apps/nodejs/bin/npm
  npmPackages:
    @babel/core: ^7.1.0 => 7.9.0 
    @babel/plugin-proposal-class-properties: ^7.0.0 => 7.8.3 
    @babel/preset-env: ^7.0.0 => 7.9.0 
    @babel/preset-react: ^7.0.0 => 7.9.1 
    babel-core: ^7.0.0-bridge.0 => 7.0.0-bridge.0 
    babel-eslint: ^10.0.0 => 10.1.0 
    babel-jest: ^25.1 => 25.1.0 
    babel-loader: ^8.0.0 => 8.1.0 
    eslint: ^6 => 6.8.0 
    jest: ^25.1 => 25.1.0 
    webpack: ^4.0.0 => 4.42.0 

```

**Comment by nicolo-ribaudo** [comment]
Could this be the same as https://github.com/babel/babel/issues/11304?

**Comment by andy128k** [comment]
@nicolo-ribaudo  I cannot confirm neither check. There is no render-prop in my project.

**Comment by nicolo-ribaudo** [comment]
Could you share `ProgressBar`'s source?

**Comment by NikitaSedyx** [comment]
I have the same issue, after release our tests failed

**Comment by andy128k** [comment]
@nicolo-ribaudo  There is nothing specific in my ProgressBar. All tests of my components are failing.

Anyway here it is:

```js
import React from 'react';
import style from './style.css';

export default function ProgressBar() {
  return <div className={style.progress}/>;
}
```

And here is a test:

```js
import React from 'react';
import {shallow} from 'enzyme';
import ProgressBar from './index';

describe('ProgressBar widget', function() {
  it('renders', function() {
    let wrapper = shallow(<ProgressBar />);
    expect(wrapper.prop('className')).toStrictEqual('progress');
  });
});
```

**Comment by nicolo-ribaudo** [comment]
Ok, could you share the compiled code for one of those failing components? (`ProgressBar` would be perfect, since it's super simple)

**Comment by andy128k** [comment]
Good one:

```js
function ProgressBar() {
  /* istanbul ignore next */
  cov_qf7hgggjx().f[0]++;
  cov_qf7hgggjx().s[0]++;
  return (
    /* istanbul ignore next */
    _react.default.createElement(
    /* istanbul ignore next */
    "div",
    /* istanbul ignore next */
    {
      className:
      /* istanbul ignore next */
      _style.
      /* istanbul ignore next */
      default.progress
    })
  );
}
```

Broken one:

```js
function ProgressBar() {
  /* istanbul ignore next */
  cov_qf7hgggjx().f[0]++;
  cov_qf7hgggjx().s[0]++;
  return /*#__PURE__*/
  /* istanbul ignore next */
  _react.default.createElement(
  /* istanbul ignore next */
  "div",
  /* istanbul ignore next */
  {
    className:
    /* istanbul ignore next */
    _style.
    /* istanbul ignore next */
    default.progress
  });
}
```

Classic JS error.

**Comment by nicolo-ribaudo** [comment]
Ok, this is the same as the other one then! It should be fixed by https://github.com/babel/babel/pull/11306

**Comment by bopfer** [comment]
#11306 doesn't fix things for me.  Still getting the `Nothing was returned from render` errors with the 7.9.3 packages.

Weird thing is that my tests all run fine on my local MacOS workstation.  But, they fail with the error on my CI system, which is Linux.

Downgrading to `@babel/preset-react@7.8.3` fixes things.

**Comment by nicolo-ribaudo** [comment]
@bopfer Is it possible that your CI used the old version of `@babel/generator` (which is were there was the bug)?

If not, could you add `console.log(ABrokenComponent.toString())` to see the transpiled code on CI? (or better, download the transpiled file)

**Comment by bopfer** [comment]
@nicolo-ribaudo Disregard, sorry!  Seems like CI was pulling in the old version for some reason.  I updated all my packages, rebuilt my `yarn.lock` file, and everything is working now.

**Comment by andy128k** [comment]
Was is published? npm shows 7.9.1 as a latest one here https://www.npmjs.com/package/@babel/preset-react

**Comment by nicolo-ribaudo** [comment]
Yes sorry, this was a bug in `@babel/generaror`.
