### ISSUE TITLE
@babel/parser v7.13.0 reintroduces "Cannot read property 'range' of null" for curly braces

### ISSUE THREAD

**Issue by pivotal-james-zcheng** [babel/babel#12857]
## Bug Report

- [ ] I would like to work on a fix!

**Current behavior**

Curly braces are not being correctly parsed and linted on @babel/parser version 7.13.0

Stacktrace:
```
yarn run v1.22.10
$ eslint --fix src
TypeError: Cannot read property 'range' of null
Occurred while linting /Users/user/workspace/project/frontend/app/src/App.js:1
    at OffsetStorage.setDesiredOffset (/Users/user/workspace/project/frontend/app/node_modules/eslint/lib/rules/indent.js:340:45)
    at TemplateLiteral.node.expressions.forEach (/Users/user/workspace/project/frontend/app/node_modules/eslint/lib/rules/indent.js:1358:29)
    at Array.forEach (<anonymous>)
    at Object.TemplateLiteral [as listener] (/Users/user/workspace/project/frontend/app/node_modules/eslint/lib/rules/indent.js:1350:34)
    at Program:exit.listenerCallQueue.filter.forEach.nodeInfo (/Users/user/workspace/project/frontend/app/node_modules/eslint/lib/rules/indent.js:1596:55)
    at Array.forEach (<anonymous>)
    at Program:exit (/Users/user/workspace/project/frontend/app/node_modules/eslint/lib/rules/indent.js:1596:26)
    at listeners.(anonymous function).forEach.listener (/Users/user/workspace/project/frontend/app/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/user/workspace/project/frontend/app/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
error Command failed with exit code 2.
```

**Input Code**

The first line of app.js is
```js 
import React, {Component} from 'react'
```
After disabling the curly linting rule, the failure is on a line that uses curly brace template strings.

**Expected behavior**
Eslint should parse and lint curly braces properly

**Environment**
- Babel version(s): v7.13.0
- Node/npm version: Node v10.16.0 / NPM 7.4.0
- OS: macOS 10.15.7
- Monorepo: no
- How you are using Babel: `webpack`

**Possible Solution**
None

Workaround - add a resolution in package.json
```
  "resolutions": {
    "@babel/parser": "7.12.17"
  },
```

**Additional context**

Related issue - https://github.com/babel/babel-eslint/issues/681

**Comment by JLHwung** [comment]
Can you post your eslint config?

**Comment by pivotal-james-zcheng** [comment]
Here it is:
```
module.exports = {
  env: {
    browser: true,
    es6: true,
    jest: true,
    node: true,
  },
  extends: [
    'plugin:react/recommended',
    'eslint:recommended',
  ],
  globals: {
    Atomics: 'readonly',
    SharedArrayBuffer: 'readonly',
    fail: false,
  },
  parser: 'babel-eslint',
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 7,
    sourceType: 'module',
  },
  plugins: [
    'react',
    'react-hooks'
  ],
  settings: {
    react: {
      version: 'detect',
    },
  },
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'comma-dangle': ['error', 'always-multiline'],
    'semi': [2, 'never'],
    'quote-props': ['error', 'as-needed'],
    'indent': ['error', 2, {
      'SwitchCase': 1,
      ignoredNodes: [ 'JSXAttribute' ],
    }],
    'prefer-const': "error",
    'quotes': ["error", "single"],
  },
}
```

**Comment by nicolo-ribaudo** [comment]
@pivotal-james-zcheng I believe this error was fixed in `@babel/eslint-parser`, which is the new version of `babel-eslint` (the last `babel-eslint` version is from more than one year ago).

**Comment by pivotal-james-zcheng** [comment]
@nicolo-ribaudo  Thank you for the prompt response. We are on `"babel-eslint": "10.1.0"`. We have attempted to update to `@babel/eslint-parser` when we saw this error, but the error persists.

From our observations:
1. using `"babel-eslint": "10.1.0"` and resolutions of `"@babel/parser": "7.12.17"`, everything works
2. using `"babel-eslint": "10.1.0"` and resolutions of `"@babel/parser": "7.13.0"`, we see the "Cannot read property 'range' of null" error for curly braces
3. using `"babel-eslint": "10.1.0"` and resolutions of `"@babel/parser": "7.13.4"`, everything works again

Since updating @babel/eslint-parser to v7.13.4 solves this error for us, I will close this issue.

**Comment by pivotal-james-zcheng** [comment]
To elaborate, before v7.13.x was released, we were able to not set any resolutions for `@babel/parser` in packages.json. 

After v7.13.x was released, we have to set a resolution of `"@babel/parser": "7.12.17"` or `"@babel/parser": "7.13.4"`, otherwise we will get the "Cannot read property 'range' of null" error

**Comment by nicolo-ribaudo** [comment]
Then this is somehow related to https://github.com/babel/babel/issues/12864 (the only eslint or parser issue we fixed), even if I'm not sure how.

If you could create an reproduction with v7.13.0 and add it as a test in a PR to this repo, it would help preventing it from happening again in the future :pray:
