### ISSUE TITLE
Error with latest @babel/helper-create-class-features-plugin (v7.13.0)

### ISSUE THREAD

**Issue by skalyanmoguloju** [babel/babel#12853]
Received message:   "_typeof is not a function"
      at _possibleConstructorReturn (node_modules/@babel/runtime/helpers/possibleConstructorReturn/index.js:6:16)

**Comment by nicolo-ribaudo** [comment]
Which is your `@babel/runtime` versino?

**Comment by skalyanmoguloju** [comment]
I did not specifically update my project to pull in the latest version. 
Regarding the babel/runtime version I have 7.13.0

**Comment by nicolo-ribaudo** [comment]
Linked to the wrong PR, this is fixed in v7.13.2.

**Comment by skalyanmoguloju** [comment]
Thank you @nicolo-ribaudo

**Comment by dlong500** [comment]
@nicolo-ribaudo I have @babel/runtime 7.13.2 with webpack5 and still have a problem:
`_interopRequireDefault is not a function`

**Comment by dlong500** [comment]
Yikes, this is a bit of a mess.  I tried rolling back to 7.12.x but a clean install now pulls in a bunch of dependencies using babel 7.13.x that still breaks the application (such as dom-helpers used by react-transition-group).  I guess I'll just go to bed for now...

**Comment by JoeeeeeWu** [comment]
@nicolo-ribaudo  I have @babel/runtime 7.13.2 with webpack5 and still have a problem:
_interopRequireDefault is not a function

this problem is not solved......
