### ISSUE TITLE
[Bug]: Function's Implicit Arguments Binding Fail

### ISSUE THREAD

**Issue by clhiker** [babel/babel#13990]
### 💻

- [X] Would you like to work on a fix?

### How are you using Babel?

@babel/cli

### Input code

```js
var arguments = [1, 2, 3];
var arr = () => arguments[0];
function foo(n) {
    var f = () => arguments[0] + n; // foo's implicit arguments binding. arguments[0] is n
    return f();
}
console.log(foo(3)); // 6
```
Here is the [REPL](https://babel.dev/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=AQNwhgTskOYK4FsCmA7ALgZ2AXmAbQEYAaYAJhIGYBdAbgChRJoIpcAKAShwD5n5l0GPAAZaDBpAicawAPSzgBccABmcFAGM0ASwD2KVbt1sUXAN4NgjKCpzBOPPolSYRVYAGpgKGfMO6AcixtBAAHABttDW00JwFMYAAjbRQAExSYADo4lyFRYG0sFEtgCCQ0OAgDFWkGAF9lDX0MXXCkTPDdGDYVIzYKDg5fBQA2IA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=true&presets=env%2Cflow&prettier=false&targets=&version=7.16.4&externalPlugins=&assumptions=%7B%7D)

### Configuration file name

babel.config.js

### Configuration

```js
module.exports = function (api) {
  api.cache(true);
  const sourceType= "unambiguous";
  const presets = [
      ["@babel/preset-env", { "modules": false}]
  ];
  const plugins = [  ];

  return {
    sourceType,
    presets,
    plugins
  };
}
```

### Current behavior and Expected behavior
The output run by node transformed by babel is 4, but it should be 6.
The foo's implicit arguments binding. arguments[0] should be n.

### Environment

- babel 
- - ├── @babel/cli@7.16.0
- - ├── @babel/preset-env@7.16.0
- Node: [v16.11.1]
- npm version [8.0.0]
- os [ubuntu 20.04]

**Comment by The-x-Theorist** [comment]
I'd like to work on this issue?

**Comment by The-x-Theorist** [comment]
This is issue is already fixed and it's giving the output correctly as 6 not as 4 without any changes to codebase currently.

**Comment by The-x-Theorist** [comment]
> This is issue is already fixed and it's giving the output correctly as 6 not as 4 without any changes to codebase currently.

I wrote some tests to check the current scenario and it's working fine.

**Comment by JLHwung** [comment]
I can still reproduce the issue on the OP-provided REPL link.

**Comment by The-x-Theorist** [comment]
> I can still reproduce the issue on the OP-provided REPL link.

Sorry, I got the point and I will resolve this bug soon.

**Comment by nicolo-ribaudo** [comment]
@The-x-Theorist You can test this enabling just the arrow functions plugin.
