### ISSUE TITLE
[Bug]:Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by jisao** [babel/babel#15753]
### 💻

- [ ] Would you like to work on a fix?

### How are you using Babel?

babel-loader (webpack)

### Input code

        "@babel/core": "7.9.0",
        "@babel/helper-create-regexp-features-plugin": "7.22.6",
        "@babel/helper-plugin-utils": "7.22.5",
        "@babel/plugin-proposal-class-properties": "7.8.3",
        "@babel/plugin-proposal-decorators": "7.8.3",
        "@babel/plugin-syntax-jsx": "7.22.5",
        "@babel/plugin-transform-runtime": "7.22.6",
        "@babel/polyfill": "7.12.1",
        "@babel/preset-env": "7.9.0",
        "@babel/preset-react": "7.22.5",
        "@babel/preset-stage-0": "7.8.3",
        "@babel/preset-typescript": "7.22.5",
        "babel-eslint": "10.0.3",
        "babel-jest": "24.9.0",
        "babel-loader": "8.0.6",
        "babel-plugin-import": "1.13.6",
        "babel-preset-react-app": "9.1.2",
       "happypack": "5.0.1",
        "webpack": "4.46.0",
        "webpack-bundle-analyzer": "4.9.0",
        "webpack-cli": "3.3.12",
        "webpack-dev-server": "3.11.3",
        "webpackbar": "4.0.0"

### Configuration file name

.babelrc

### Configuration

{
    "presets": [["@babel/preset-env", { "modules": false, "useBuiltIns": "usage", "corejs": "3" }], "@babel/preset-react", "@babel/preset-typescript"],
    "plugins": [
        ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": true }],
        "@babel/transform-runtime",
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        "@babel/plugin-proposal-class-properties"
    ],

    "comments": false,
    "env": {
        "test": {
            "presets": ["@babel/preset-env", "@babel/preset-stage-0", "@babel/preset-react"],
            "plugins": ["@babel/plugin-transform-runtime"]
        }
    }
}

### Current and expected behavior

ERROR in ./src/entry/index/index.js
Module build failed (from ./node_modules/happypack/loader.js):
TypeError: /Users/xiaoheshang/Desktop/his/his/hospitalization_doctor_station/src/entry/index/index.js: Cannot read property 'file' of undefined
    at Object.usagePure (/Users/xiaoheshang/Desktop/his/his/hospitalization_doctor_station/node_modules/babel-plugin-polyfill-regenerator/lib/index.js:35:48)
    at callProvider (/Users/xiaoheshang/Desktop/his/his/hospitalization_doctor_station/node_modules/@babel/helper-define-polyfill-provider/lib/index.js:178:27)
    at PluginPass.ReferencedIdentifier (/Users/xiaoheshang/Desktop/his/his/hospitalization_doctor_station/node_modules/@babel/helper-define-polyfill-provider/lib/visitors/usage.js:25:7)
    at PluginPass.newFn (/Users/xiaoheshang/Desktop/his/his/hospitalization_doctor_station/node_modules/@babel/traverse/lib/visitors.js:192:17)
    at newFn (/Users/xiaoheshang/Desktop/his/his/hospitalization_doctor_station/node_modules/@babel/traverse/lib/visitors.js:159:14)
    at NodePath._call (/Users/xiaoheshang/Desktop/his/his/hospitalization_doctor_station/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/Users/xiaoheshang/Desktop/his/his/hospitalization_doctor_station/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/Users/xiaoheshang/Desktop/his/his/hospitalization_doctor_station/node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (/Users/xiaoheshang/Desktop/his/his/hospitalization_doctor_station/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/xiaoheshang/Desktop/his/his/hospitalization_doctor_station/node_modules/@babel/traverse/lib/context.js:65:19)

### Environment

All projects started or packaged locally today with this issue

**Comment by Sapython** [comment]
Angular is also broken because of this issue. https://github.com/angular/angular-cli/issues/25496

**Comment by nicolo-ribaudo** [comment]
Can you still reproduce this issue with version 7.22.8 of `@babel/core` and `@babel/traverse`?

**Comment by Sapython** [comment]
It's fixed with babel version `7.22.8` of `@bable/core`. For angular I deleted by `package-lock.json` and `node_modules` to resolve it.

**Comment by jisao** [comment]
Using @bable/core version 7.22.8 can solve this problem

**Comment by mshima** [comment]
It was not fixed for our use case.
The error was introduced before babel v7.22.7, not sure if at v7.22.6 or a transitive dependency. First failure is from 18 hours ago (before v7.22.7) https://github.com/jhipster/generator-jhipster-react-native/actions/runs/5467660427/jobs/9954258684.
I've updated a working package-lock to `@babel/core@7.22.6` and it's working as expected. Recreating package-lock breaks the test.
I am pretty sure `@babel/transform` by itself is not the root cause. v7.22.7 may have triggered for others use cases.


For some reason babel is behaving something like:
```
  function foo(bar) { // passing bar = {}
    console.log(bar.foo); // prints foo
    console.log(bar.foo); // prints foo
  }
```

**Comment by logancooper-tylertech** [comment]
We were seeing this issue on 7.22.27 last night, but it appears to have been resolved by pulling 7.22.28

**Comment by nicolo-ribaudo** [comment]
@mshima That looks like a different issue, since the error is thrown by the generated code and not while compiling. Could you open a new issue, with steps I can use to reproduce it?

**Comment by milesyang0220** [comment]
For me, manually installing @babel/traverse@7.22.6 is a potential workaround solution.
