### ISSUE TITLE
Multiline babel-node repl.

### ISSUE THREAD

**Issue by piyushchauhan2011** [babel/babel#1741]
I noticed that node repl has multiline support while babel-node doesn't support multiline input.

**Comment by mikeybox** [comment]
@piyushchauhan2011 @sebmck Either this has been fixed or the issue isn't multiline support.
Tested on bable-node 5.6.3

**Comment by ameyms** [comment]
@piyushchauhan2011 @sebmck Thats right. Doesn't seem to be a problem anymore.

**Comment by mwq27** [comment]
How do you enter multiline mode in babel-node?  it's still not working.

**Comment by sebmck** [comment]
It'd depend on your version of node or io.js. Can everyone who's tested it
please provide their version and whether it works or not?

On Thursday, 25 June 2015, Marques Woodson <notifications@github.com> wrote:

> How do you enter multiline mode in babel-node? it's still not working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel/issues/1741#issuecomment-115089066>.
>


-- 
Sebastian McKenzie

**Comment by piyushchauhan2011** [comment]
@sebmck 
![screen shot 2015-06-25 at 2 06 49 pm](https://cloud.githubusercontent.com/assets/693487/8346666/7ef0ac62-1b43-11e5-902d-d20d53dd883e.png)

**Comment by mikeybox** [comment]
Ok updated to 0.12. and I'm getting the same error. @sebmck I can take a look at this if thats helpful.

**Comment by sebmck** [comment]
Sure, I think the REPL in 0.12 and iojs was changed to be "smarter" about multilines. Previously it'd consider any syntax errors to just mean multiline code. That's the only way to catch it for Babel though so that functionality may have to be replicated.

**Comment by mikeybox** [comment]
@sebmck It's a raised issue with node so I've submitted a pull request that will hopefully be accepted or they'll implement their own fix. In the mean time we can either take the forked REPL fix and add to Babel as a temp patch or wait and see. The REPL fix will require a minor tweak in babel node to pass a custom check function for recoverable errors.

**Comment by discotroll65** [comment]
@mikeybox ,  any status on this? I guess as a work around we can just use node 0.11, before the REPL was made "smarter" ?

**Comment by discotroll65** [comment]
Actually, using nvm just tried babel-node on v0.11.16 -- bug same bug is there too. v0.10.40 works though.

**Comment by piyushchauhan2011** [comment]
:+1:  @discotroll65

**Comment by lydell** [comment]
jashkenas/coffeescript#3388

**Comment by mikeybox** [comment]
@discotroll65 unfortunately I've not had any movement on the pull request I submitted to the Node.js guys so at the moment it's in limbo. @sebmck may have some thoughts on the matter but essentially it's Node's implementation of REPL that breaks the multiline support in third party libraries.  At the moment if your code doesn't require a newer version of Node then yeah use that until there's a better solution.

**Comment by sebmck** [comment]
Closing this as `babel-node` just uses the node API and whatever issues with it aren't the result of Babel.

**Comment by ajwhite** [comment]
Hrmm, @kittens I came across a difference in behavior between `babel-node` and `node` -- check it out:

![example](http://g.recordit.co/VvOOmj39tn.gif)
