### ISSUE TITLE
babylon v5.7.5 fails to install

### ISSUE THREAD

**Issue by tomekwi** [babel/babel#2043]
Have a look: https://travis-ci.org/studio-b12/less-index/jobs/71977829#L102

**Comment by tomekwi** [comment]
BTW, I have exactly the same output on my local machine. It is so since around 10 minutes.

**Comment by bdefore** [comment]
:+1: @tomekwi i'm having the same issue

**Comment by tmoitie** [comment]
Looks like a few versions have been pulled from npm.

**Comment by kahwee** [comment]
came to report the same thing. 

```
npm ERR! notarget No compatible version found: babylon@'>=5.7.5 <6.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","5.6.23","5.7.1","5.7.2"]
```

**Comment by sebmck** [comment]
They weren't pulled, they were just never released because the publish script failed mid-publish.

**Comment by sebmck** [comment]
Fixed.

**Comment by kahwee** [comment]
Thanks @sebmck

**Comment by tomekwi** [comment]
Wow @sebmck, thanks for the quick reaction!

I still have some problems though :( https://travis-ci.org/studio-b12/less-index/jobs/71977829#L113 (same on my machine).

**Comment by bdefore** [comment]
updating to 5.8.2 gives me the same error as @tomekwi

**Comment by sebmck** [comment]
Fixing

**Comment by sebmck** [comment]
Force pushed a release of 5.8.3. Seems to have fixed it, dunno what went wrong.

**Comment by iamstarkov** [comment]
@sebmck fixed! thanks a lot

**Comment by tomekwi** [comment]
:+1: works like a charm!

**Comment by tomekwi** [comment]
Thanks! :beer:

**Comment by marnen** [comment]
Thanks for the fix! But why does this keep happening? There are several issues like this one on this project, reporting the same problem with older releases.

**Comment by bdefore** [comment]
thanks, works here now too

**Comment by AlexBen** [comment]
Thanks a lot. Reactive problem solving!
