### ISSUE TITLE
Seems like babel-node is running very slow.

### ISSUE THREAD

**Issue by bgnorlov** [babel/babel#2706]
It took 7 seconds for running simple express-react app: 
```javascript
import express from 'express';
import mongodb from 'mongodb';
import React from 'react';
import ReactDOMServer from 'react-dom/server';

var app = express();

app.get('', function(req, res){
  var comp = ReactDOMServer.renderToString(<h1>hello world</h1>);
  res.send(comp)
});

var server = app.listen(4000);
server.close();
```
$> time node_modules/.bin/babel-node server.js
$>  7.61s user 0.78s system 101% cpu 8.264 total

My .babelrc file looks like this:
{
  "presets": ["es2015", "react", "stage-0"]
}

Am I missing something?

**Comment by kzc** [comment]
Similar babel 6.0 slowness here.

    $ mkdir ~/test6
    $ cd ~/test6
    $ npm -v
    2.14.7
    $ npm install babel-cli@6.0.14 babel-preset-es2015@6.0.14
    $ node_modules/babel-cli/bin/babel-node.js -V
    6.0.14
    $ echo "class Foo {}" > test.js
    $ time node_modules/babel-cli/bin/babel.js --presets es2015 test.js
    real  0m2.731s
    user  0m2.533s
    sys   0m0.251s

The problem seems to be the interaction between babel 6.0.x and npm 2.x.

babel 6 node modules are repeated quite a bit with the new plugin structure:

    $ find node_modules/ | wc -l
       98596
    $ find node_modules | grep es6.typed-arrays.uint8-clamped-array.js | wc -l
         140

babel 5 by comparison:

    $ mkdir ~/test5
    $ cd ~/test5
    $ npm -v
    2.14.7
    $ npm install babel@5.8.23
    $ node_modules/babel/bin/babel.js -V
    5.8.23 (babel-core 5.8.33)
    $ echo "class Foo {}" > test.js
    $ time node_modules/babel/bin/babel.js test.js 
    real  0m0.595s
    user  0m0.571s
    sys   0m0.056s
    $ find node_modules/ | wc -l
        5562
    $ find node_modules | grep es6.typed-arrays.uint8-clamped-array.js | wc -l
           2

**Comment by sebmck** [comment]
Make sure you're npm deduping. That is literally the only thing that can be causing slow initialization times.

**Comment by ArtemGovorov** [comment]
`npm dedupe` does help indeed. It seems like a significant drawback that one has to do it to make babel 6 perform well, I suspect many users don't even suspect it exists and may complain about babel 6 performance.

**Comment by GGAlanSmithee** [comment]
As more people use newer versions of `npm`,  this shouldn't be a problem, right? As it uses a flat folder structure.

**Comment by kzc** [comment]
`npm dedupe` did not help my particular npm 2.14.7 setup. babel 6 was still slow.

upgrading to npm 3 and reinstalling babel 6 did work.

Do you think it's reasonable for everyone to upgrade to npm 3.x or issue special npm 2.x commands post-install to use babel 6? There are a lot of npm 2.x babel users out there that will be affected by this.

**Comment by jontelm** [comment]
Yes, update npm and reinstall works.

**Comment by GGAlanSmithee** [comment]
I don't think it's unreasonable to have npm version >= 3 as a requirement (or to strongly suggest it, like flow does when using an older node version) as long as it's properly documented.

**Comment by sebmck** [comment]
Closing as there's nothing actionable here. I've released a separate [`babel-doctor`](https://babeljs.io/blog/2015/11/03/babel-doctor/) utility that will help diagnose issues like this in the future.

**Comment by kzc** [comment]
@sebmck for a node 4.2.1/npm 2.14.7 installed babel, babel-doctor reports:

    Recommend running `npm dedupe`

Running this command did not resolve the issue.

The following text would save babel 6 users a lot of time and frustration:

    Recommend reinstalling babel with npm@3.3.6 or greater.

**Comment by sebmck** [comment]
Good call. Should add an npm 3 rule to `babel-doctor`.
