### ISSUE TITLE
"es3-member-expression-literals" not transforming injected 'exports.default'

### ISSUE THREAD

**Issue by loganfsmyth** [babel/babel#2817]
I assume the commonjs transform is doing something that makes traversal not run over it.

Content:

    export default {};

Config:
```
{
    "plugins": [
        "transform-es3-member-expression-literals",
        "transform-es2015-modules-commonjs",
    ]
}
```

Output:
```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = {};
```

Originally reported in http://stackoverflow.com/questions/33512715/babel-6-0-20-modules-feature-not-work-in-ie8

**Comment by jontelm** [comment]
Maybe related to the problems I see in transform-es3-property-literals
test-script.js
```
import App from '/test/test.js'
```
In 5.8.29:
```
babel test-script.js
```
```
'use strict';

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }
var _testTestJs = require('/test/test.js');
var _testTestJs2 = _interopRequireDefault(_testTestJs);
```
In 6.1.1 (babel-core 6.0.20)
```
babel --presets es2015 test-script.js --plugins transform-es3-property-literals
```
```
'use strict';

var _test = require('/test/test.js');
var _test2 = _interopRequireDefault(_test);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

{ default: obj } should be { 'default': obj }  ?

**Comment by thejameskyle** [comment]
It appears that it's never visiting the new MemberExpression on exit.

Example repo: https://github.com/thejameskyle/__babel-bug-2817

**Comment by shadowmint** [comment]
This also affects imports in the form `import $ from 'jquery'`, which expand `$(...)` to `_jquery2.default(...)`, causing the same issue even when the es3 plugins are installed.

Babel version: 
```
    "babel-core": "^5.7.2",
    "babel-plugin-transform-es2015-modules-amd": "^6.0.15",
    "babel-plugin-transform-es3-member-expression-literals": "^6.0.14",
    "babel-plugin-transform-es3-property-literals": "^6.0.14",
```

**Comment by Witcher42** [comment]
Maybe you can try to change the order of plugins like:

```
{
    "plugins": [
        "transform-es2015-modules-commonjs",
        "transform-es3-member-expression-literals",
    ]
}
```

**Comment by jontelm** [comment]
@Witcher42 Same result.

**Comment by joshacheson** [comment]
What would be the "Babel way" of solving this issue? Is there a way for a plugin like `es3-member-expression-literals` to revisit compiled code? Should using the literal `exports['default']` as opposed to `exports.default` be a feature of `transform-es2015-modules-commonjs` in loose mode? I've solved this (veryyyyyy hackishly) in my own fork and would like to contribute (with a proper solution), but it's tough to know where to begin because I want to use practices that suit the rest of the Babel codebase.

Cheers!

**Comment by stevenjob** [comment]
Should this be reopened?

**Comment by hzoo** [comment]
Should be fixed by https://github.com/babel/babel/pull/4518?

**Comment by danez** [comment]
Yes the common js plugin should also work with classes with the pr. Amd and umd are still not working, but this issue is only about common js
