### ISSUE TITLE
`babel-register@6.1.4` depends on a old version of `babel-runtime`

### ISSUE THREAD

**Issue by timnew** [babel/babel#3012]
I have `babel-core@6.1.4` installed. 

When I call `require('babel-core/register')`, it yields

```
> require('babel-core/register')
Error: Cannot find module 'babel-runtime/helpers/interop-require-default'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/timnew/Workspace/bi/log-to-email/node_modules/babel-register/lib/node.js:5:30)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```
I dig into the code, and found it is caused by `babel-register` compiled code depends on a old version of `babel`:

I found following code in `node_modules/babel-register/lib/node.js`:

```js
var _interopRequireDefault = require("babel-runtime/helpers/interop-require-default")["default"];

var _interopRequireWildcard = require("babel-runtime/helpers/interop-require-wildcard")["default"];
```

But in `babel-runtime@6.1.4`, file name conversion has been changed from `dash` to `pascal`.

So the file should be `interopRequireDefault` instead of `interop-require-default`

**Comment by timnew** [comment]
Not sure how to fix this issue, since the source code is correct, the issue is the compiled code depends on a incompatible runtime.

**Comment by magicismight** [comment]
+1
running to this issue when compiling async functions

**Comment by nightwolfz** [comment]
Same here

**Comment by thealjey** [comment]
same as the now closed #2989

**Comment by thewillhuang** [comment]
you have to move babel from dev dependencies to dependencies inside package.json

**Comment by thealjey** [comment]
@thewillhuang who are you saying this to?

**Comment by Industrial** [comment]
+1 on this one

**Comment by sebmck** [comment]
This has been fixed in 6.1.18.

**Comment by Industrial** [comment]
I still have this issue, with babel-core set to * in my package.json.

`git clone https://github.com/Industrial/id-builder; cd id-builder; npm install; node idBuilder.js;` will yield the error.
