### ISSUE TITLE
No compatible version found: babel-runtime@^6.20.0

### ISSUE THREAD

**Issue by jimtom2713** [babel/babel#4975]
Trying to install babel-polyfill (for example) results in an error from npm that there is no compatiable version for babel-runtime@6.20.0. This seems to be the current version here in the repo but doesn't appear to have been published to npm. 

### Input Code
npm install babel-polyfill

### Babel Configuration (.babelrc, package.json, cli command)
```js
{
   "presets": ["es2015", "stage-0", "react"],
   "plugins": ["syntax-async-functions","transform-regenerator", "transform-runtime"]
}
```

### Context
I can no longer install, via npm install, babel-runtime dependencies as they seem to be upgrading to require babel-runtime 6.20.0 but npm does not have that version.

### Your Environment

| software         | version
| ---------------- | -------
| Babel            |  
| node             | 
| npm              | 
| Operating System | 
![screen shot 2016-12-08 at 4 38 56 pm](https://cloud.githubusercontent.com/assets/5955421/21033665/eff7ee36-bd66-11e6-9b46-2b6cab4006c6.png)

**Comment by hzoo** [comment]
Werid it should be there? https://unpkg.com/babel-runtime@6.20.0/

**Comment by jimtom2713** [comment]
On the search page from npm, search for babel-runtime, it shows a version number of 6.20.0 but that doesn't match what npm tries to pull.
![screen shot 2016-12-08 at 5 14 25 pm](https://cloud.githubusercontent.com/assets/5955421/21034082/e71de36c-bd69-11e6-8946-4f98dd2d3d53.png)

**Comment by bitfrost** [comment]
We are seeing this as well, causing havok with some of our ci builds.

**Comment by hzoo** [comment]
It might be a caching issue if you aren't on the public npm registry?

**Comment by jimtom2713** [comment]
npm has the latest version of babel-runtime listed as 6.18.0 not 6.20.0

**Comment by existentialism** [comment]
@jimtom2713 `npm view babel-runtime version` returns 6.20.0 for me?

**Comment by jmhwang7** [comment]
Also seeing 6.18.0 here: https://www.npmjs.com/package/babel-runtime

**Comment by bitfrost** [comment]
npm appears to be catching up now.  mpmjs.com  website though is still show older versions

**Comment by jimtom2713** [comment]
Still unable to install it. @bitfrost were you successful?

**Comment by bitfrost** [comment]
yes,  it  appears to be working for us now.   Website still reports the older version.
https://www.npmjs.com/package/babel-runtime

**Comment by jmhwang7** [comment]
This is still an issue for us. @jimtom2713, how about you?

**Comment by existentialism** [comment]
@jmhwang7 curious, what does `npm view babel-runtime version` return?

**Comment by jimtom2713** [comment]
@jmhwang7 This is still an issue for us as well.
@existentialism 
```
npm view babel-runtime version
> 6.18.0
```

**Comment by alayek** [comment]
Oddly enough, running `npm install` locally works. I guess that's because it's picking up from the cache.

Running in CI fails. Running `yarn install` instead of `npm install` in CI, and fails at the resolving dependency stage:

```shell
error Couldn't find any versions for "babel-runtime" that matches "^6.20.0"
```

**Comment by DrewML** [comment]
@alayek You're definitely still hitting caching issues.

```sh
└─▪ npm view babel-traverse version
6.20.0
```

**Comment by alayek** [comment]
@DrewML thanks. I will clean the yarn and npm cache, and try once again.

**Comment by alayek** [comment]
Can confirm that this has been resolved now. CI installs as well as local installs work fine.

--

I would like to understand what caused this issue, and how such things can be prevented in future, when a new set of babel-runtime and other packages are published.

If I am not much mistaken, similar issues have been reported before: https://github.com/babel/babel/issues/4437

**Comment by Solvegam** [comment]
Hi, could someone help with finding package which depends on babel-runtime - how can it be done and is it possible to hardcode version inside this package?

**Comment by alayek** [comment]
@Solvegam Maybe you are looking for `npm ls babel-runtime`?

**Comment by Solvegam** [comment]
As far as I understand there is transitive dependency. Because all babel packages I use have fixed versions

**Comment by trigun539** [comment]
Anyway to force npm to download the latest version. Tried npm cache clean, but still running into issues saying babel-runtime@6.20.0 not found. Latest I see is 6.18.0.

Any ways to get around this?

**Comment by Solvegam** [comment]
I have just rebuild the project and it found 6.20.0 version. So lazy decision is to wait  until you will be able to get the latest not cached  version, but as for me this issue must be handled somehow.

**Comment by atheeq** [comment]
Running into an issue with babel-code-frame. 
npm ERR! No compatible version found: babel-code-frame@^6.20.0
Its still cached. Any workarounds?

**Comment by jmhwang7** [comment]
The issue's resolved for us. It's finding 6.20.0.

**Comment by jimtom2713** [comment]
The issue is resolved for us now as well. Cleaned the cache again this morning and I guess second time is the charm.
```
npm view babel-runtime version
> 6.20.0
```

**Comment by hzoo** [comment]
This is happening a lot after the release so we'll need to investigate more. I'm not actually sure how we will find out the underlying cause but it must have to do with the way we are using lerna to publish. Sorry about the trouble! It does seem to be solved due to clearing caching though.

I usually check via `npm view package verson` or `npm view package dist-tags` or just using `unpkg.com/package/`

**Comment by JWess** [comment]
I tried cleaning my cache, and I'm still having this problem:

npm view babel-runtime version
6.18.0

**Comment by JWess** [comment]
10 mins later (after clearing my npm cache), it is now working:

npm view babel-runtime version
6.20.0

**Comment by egrivel** [comment]
It seems that parts of babel started to require babel-runtime@6.20.0 before that version had fully propagated to all the servers. It makes me wanting to drop babel and look for another solution, because right now my emergency fix was delayed by a couple of hours because of a babel dev dependency failure.
 
Should I consider this a one-time mistake by the babel team, or should I expect this to happen again in the future?

**Comment by loganfsmyth** [comment]
@egrivel Sorry you had issues with your deploy, that's certainly not the level of reliability that we aim to provide.

Do you use a third-party npm mirror like https://github.com/rlidwka/sinopia? As far as we know, this isn't an issue when hitting npm itself, so it isn't related to propagating to npm's servers, but rather a case where _some_ packages end up in third-party mirrors, while depending on other packages that have yet to end up in those mirrors.

**Comment by egrivel** [comment]
@loganfsmyth It's not just me, there were a lot of people having problems and having to wait for some propagation to happen. As of right now, https://www.npmjs.com/package/babel-runtime lists 6.18.0 as the latest version of babel-runtime.

I'm relatively new to NPM but it seems something went wrong with this update. People who are using fixed versions of babel packages are stuck because somehow dependencies are not synchronized.

In my naivity I would expect that first babel-runtime would release a 6.20.0 version and that update would be allowed to percolate through the Internet before other packages would start using it. But it almost seems like some package came out with a dependency on 6.20.0 before that version was fully established, and my code had a hidden dependency on that package. Hence my question if this is something that happens often or if this is a fluke.

**Comment by loganfsmyth** [comment]
@egrivel 

> As of right now, https://www.npmjs.com/package/babel-runtime lists 6.18.0 as the latest version of babel-runtime.

I'd very much caution against that specific method for checking the current version, npm's website is aggressively cache and can take days to update, independent of what is actually available via the npm registry itself. The correct method to check what is available is `npm dist-tags ls babel-runtime`. That could however return stale results if you are using a mirror that has had an error.

> I'm relatively new to NPM but it seems something went wrong with this update. 

I totally agree. As far as we're aware this only occurs when using third-party registry/mirror systems, so it's possible that the issue is with their logic for invalidating caches. Potentially there is something we are doing in our publish process that increases the probability of issues like this happening.

> In my naivity I would expect that first babel-runtime would release a 6.20.0 version and that update would be allowed to percolate through the Internet before other packages would start using it.

npm is a centralized registry, so by default there isn't anywhere to percolate. That's the core of the confusion around this for us, and why this issue is likely with npm registry mirrors.

> Hence my question if this is something that happens often or if this is a fluke.

It has happened before and I can't promise it won't happen again until we are able to nail down why third-party mirrors run into these issues. If you are using the npm registry itself, we never expect any issues..

**Comment by hzoo** [comment]
Sorry everyone, we'll try to look into this more!

**Comment by marchaos** [comment]
Seeing this again today. Any idea why this was happening? I assume it's because the release was done only moments ago (6.26.0). Perhaps it's a npmjs cache issue?

**Comment by hzoo** [comment]
noo.. yeah. might be resolved in a bit but there might be dependency cycles where one gets published out of order in 6.x.

**Comment by ashishtechie** [comment]
Any update on this issue?

**Comment by hzoo** [comment]
same as https://github.com/babel/babel/issues/6126
