### ISSUE TITLE
"unexpected token import" error with ava

### ISSUE THREAD

**Issue by rollymaduk** [babel/babel#6036]
Choose one: Bug Report

setting up AVA with babel fails consistently with unexpected token import error

### Input Code

[sample-repo](https://github.com/rollymaduk/wallaby-ava-CRNA-test)

###Package.json
```js
{
  "name": "MyNewProject",
  "version": "0.0.0",
  "description": "",
  "author": "",
  "private": true,
  "main": "node_modules/expo/AppEntry.js",
  "dependencies": {
    "expo": "^19.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz"
  },
  "devDependencies": {
    "@ava/babel-preset-stage-4": "^1.1.0",
    "ava": "^0.21.0",
    "babel-eslint": "^7.2.3",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.23.0",
    "babel-preset-env": "^1.6.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-react-native": "^2.1.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-register": "^6.24.1",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.2",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0",
    "eslint-plugin-react-native": "^2.3.2",
    "flow-bin": "^0.51.0",
    "react-dom": "16.0.0-alpha.12"
  },
  "scripts": {
    "storybook": "storybook start -p 7007",
    "test": "ava"
  },
  "ava": {
    "files": [
      "**/*.test.js",
      "!node_modules/**/*.test.js"
    ],
    "babel": "inherit",
    "concurrency": 5,
    "failFast": true,
    "failWithoutAssertions": false,
    "tap": true,
    "powerAssert": false,
    "require": [
      "babel-register","babel-polyfill"
    ]
  }
}

```

### Babel Configuration (.babelrc, package.json, cli command)

```js
{
  {
  "presets": [
    "@ava/stage-4",
    "@ava/stage-4",
    "react-native",
    "stage-0",
    "env",
    "babel-preset-expo",
    "react-native-stage-0/decorator-support",

  ],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  }

}

}
```

### Expected Behavior
It should transpile my source and test files successfully allowing my ava tests to run when I 

### Current Behavior
returns error
```js
TAP version 13
/home/ronald/WebstormProjects/wall-test/node_modules/expo/src/Expo.js:3
import ReactNative, { NativeModules } from 'react-native';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._extensions..js (module.js:579:10)
    at require.extensions.(anonymous function) (/home/ronald/WebstormProjects/wall-test/node_modules/babel-register/lib/node.js:152:7)
    at extensions.(anonymous function) (/home/ronald/WebstormProjects/wall-test/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ronald/WebstormProjects/wall-test/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ronald/WebstormProjects/wall-test/utility/loadAssets/cache_font.js:1:1)
    at Module._compile (module.js:570:32)
    at loader (/home/ronald/WebstormProjects/wall-test/node_modules/babel-register/lib/node.js:144:5)
    at require.extensions.(anonymous function) (/home/ronald/WebstormProjects/wall-test/node_modules/babel-register/lib/node.js:154:7)
    at extensions.(anonymous function) (/home/ronald/WebstormProjects/wall-test/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ronald/WebstormProjects/wall-test/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ronald/WebstormProjects/wall-test/utility/loadAssets/index.js:1:1)
    at Module._compile (module.js:570:32)
    at loader (/home/ronald/WebstormProjects/wall-test/node_modules/babel-register/lib/node.js:144:5)
    at require.extensions.(anonymous function) (/home/ronald/WebstormProjects/wall-test/node_modules/babel-register/lib/node.js:154:7)
    at extensions.(anonymous function) (/home/ronald/WebstormProjects/wall-test/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ronald/WebstormProjects/wall-test/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ronald/WebstormProjects/wall-test/utility/index.js:1:1)
    at Module._compile (module.js:570:32)
    at loader (/home/ronald/WebstormProjects/wall-test/node_modules/babel-register/lib/node.js:144:5)
    at require.extensions.(anonymous function) (/home/ronald/WebstormProjects/wall-test/node_modules/babel-register/lib/node.js:154:7)
    at extensions.(anonymous function) (/home/ronald/WebstormProjects/wall-test/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ronald/WebstormProjects/wall-test/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ronald/WebstormProjects/wall-test/utility/index.test.js:2:1)
    at Module._compile (module.js:570:32)
    at extensions.(anonymous function) (/home/ronald/WebstormProjects/wall-test/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/home/ronald/WebstormProjects/wall-test/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ronald/WebstormProjects/wall-test/node_modules/ava/lib/test-worker.js:61:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
# utility/index.test.js exited with a non-zero exit code: 1
not ok 1 - utility/index.test.js exited with a non-zero exit code: 1

1..0
# tests 0
# pass 0
# fail 1

```

### Context
set up AVA tests for my react native app project

### Your Environment

| software         | version(s)
| ---------------- | -------
| Babel            |  6.24 
| node             | 8.2.1
| npm              | 4.5
| Operating System | Ubuntu 17.04

**Comment by hzoo** [comment]
Can you reduce the config? There's a lot of things that aren't actually used in package.json, and presets that are doing the same things 

```
    "@ava/stage-4",
    "@ava/stage-4",
    "react-native",
    "stage-0",
    "env",
    "babel-preset-expo",
    "react-native-stage-0/decorator-support",
```

are all of those necessary? env/stage-0 should cover everything already

**Comment by rollymaduk** [comment]
@hzoo, thanks for your response, actually I kind of started off with simple config in the package.json and babelrc, I started throwing things in there after the simple config did not work in the hope that ill hit upon some right permutation but with little luck :(, I have trimmed it down like suggested but error persists.

**Comment by hzoo** [comment]
What I mean is that having less should fix it, not more 😄 , if it's just the import that's failing that would already be covered with just `env`, otherwise it means that it's not picking up the config at all.

**Comment by rollymaduk** [comment]
yeah I agree with you, and yes I did less and its still not working, thats what I meant by trim down :)  but it's still not working.. please your help will be greatly appreciated because this thing has taken off some significant hours from my earth life :(

**Comment by rollymaduk** [comment]
Hi @hzoo, please did you have time to repro the issue with  [this repo](https://github.com/rollymaduk/wallaby-ava-CRNA-test), or resolve it? your help will be greatly appreciated! thank you.

**Comment by jridgewell** [comment]
Try stack overflow.
