### ISSUE TITLE
Variable redeclarations are not recognized as modifications

### ISSUE THREAD

**Issue by RubenVerborgh** [babel/babel#6217]
### Input Code
```js
var a = 1;
var a = 2;
var b = 1, b = 2;
```
### Babel Configuration (.babelrc, package.json, cli command)
Default.

### Expected Behavior
Babel recognizes that `a` and `b` are not constants.

### Current Behavior
Babel reports that `a` and `b` are constants.

### Possible Solution
In babel-traverse, `registerBinding` incorrectly assumes that each variable name of a declaration is a new name and does not exist yet in the bindings.

### Context
The incorrect constantness assumption breaks babel-minify (https://github.com/babel/minify/issues/685).

### Your Environment
All.

**Comment by jridgewell** [comment]
This was fixed in #5745.

**Comment by RubenVerborgh** [comment]
This does not seem to be fixed; still fails in latest `master`, which includes #5745.
