### ISSUE TITLE
Parser `decorators` plugin option `decoratorsBeforeExport` no longer defaulting

### ISSUE THREAD

**Issue by jaydenseric** [babel/babel#8562]
## Bug Report

**Current Behavior**
In a recent v7 release (maybe even the final?), the parser `decorators` plugin option `decoratorsBeforeExport` no longer defaults as it used to.

```js
const { parse } = require('@babel/core')

const result = parse(code, {
  parserOpts: {
    plugins: [
      'decorators'
    ]
  }
})
```

Results in an error:

```
/Users/jaydenseric/Sites/demo/node_modules/@babel/core/lib/transformation/normalize-file.js:209
    throw err;
    ^

Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean.
```

This is unexpected, as [the `decoratorsBeforeExport` option is meant to default to `false`](https://babeljs.io/docs/en/babel-parser#plugins-options). Manually providing the same value as the supposed default works:

```diff
  const result = parse(code, {
    parserOpts: {
      plugins: [
-       'decorators'
+       ['decorators', { decoratorsBeforeExport: false }]
      ]
    }
  })
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Babel Configuration (.babelrc, package.json, cli command)**

N/A.

**Environment**
- Babel version(s): v7.0.0
- Node/npm version: Node.js v10.9.0, npm v6.4.0
- OS: macOS
- Monorepo [e.g. yes/no/Lerna]: No
- How you are using Babel: [e.g. `cli`, `register`, `loader`]: API

**Possible Solution**

**Additional context/Screenshots**

**Comment by loganfsmyth** [comment]
This was a purposeful change in #8465 for now because the spec authors haven't settled on one or the other. To avoid us choosing the wrong default, we opted to require users to choose.

In the short term, I'd expect users transitioning from `6.x` to use `legacy: true` anyway.

**Comment by jaydenseric** [comment]
Maybe the docs should be updated to reflect that there is no longer a default. Encountered the issue when reinstalling node_modules for `jsdoc-md` here: https://github.com/jaydenseric/jsdoc-md/blob/v1.5.0/lib/jsdocCommentsFromCode.js#L16

**Comment by loganfsmyth** [comment]
Totally, happy to leave this open to we can address the docs. FYI, you may want to consider using `'decorators-legacy` since that is what was supported in 6.x.

Also, in the long run, since you're using `babel/core`'s `parse`, you could pass it a filename and remove decorators entirely and rely on your users having a Babel config file that enables the proper `decorators` proposal on their side.

**Comment by the-simian** [comment]
I'm struggling with this right now, when I set this:
```
      [
        require('@babel/plugin-proposal-decorators'),
        { decoratorsBeforeExport: false, legacy: true }
      ],
```
OR
```
      [
        require('@babel/plugin-proposal-decorators'),
        { decoratorsBeforeExport: true, legacy: true }
      ],
```

For both I get the same error `'decoratorsBeforeExport' can't be used with legacy decorators.`

if I remove the `legacy` flag, like this:
```
      [
        require('@babel/plugin-proposal-decorators'),
        { decoratorsBeforeExport: false }
      ],
``

I get "The new decorators proposal is not supported yet. You must pass the `"legacy": true` option to @babel/plugin-proposal-decorators". 


if I remove the `decoratorsBeforeExport` entirely and just do the legacy flag,
` [require('@babel/plugin-proposal-decorators'), { legacy: true }],`

I am able to proceed...

I am just posting this because this was my own experience.

**Comment by nicolo-ribaudo** [comment]
Just using `{ legacy: true }` should work. What error are you getting?

**Comment by the-simian** [comment]
Its not giving me a message like the others, just 'failed to compile'. when I change the files to 

```
@something
class Thing
...
export default Thing;
```

that works. I'm not really sure what's wrong but in the previous beta this worked, and for me at least in 7 its not. If you're telling me that's a config that works, its possible the error is in eslint or something. I mainly wanted to confirm that's the correct config, but I am getting breaks on situations where there are dercorators before export and I was not beforehand

**Comment by nicolo-ribaudo** [comment]
Sorry y'all, I was confused with another issue. Our parser has two diffrent plugins: `decorators` (which is the _new_ decorators proposal) and `decorators-legacy`. If you want the old behavior, you should use `decorators-legacy`.

**Comment by the-simian** [comment]
@nicolo-ribaudo  I'll answer your questions first: 
I am indeed using `@babel/plugin-proposal-decorators`  at 7.0.0. I was using this in the 7 beta as well.
I am using `babel-eslint` at 9.0.0 also.

I am a bit confused on what is meant about the new/old proposal. I have been using this 'new' proposal lib and only with the release of 7.0.0 did it break.  I'm using and have been using the *new* behavior. However, I am not sure what the expectation right now in this proposal plugin should be. I was under the impresion that there was *no consensus yet* on before or after export (such as in this thread) https://github.com/tc39/proposal-decorators/issues/69 and that the plugin you've authored here allowed the enduser to configure, via a flag (`decoratorsBeforeExport`). 

Regardless, rather than referencing these confusing threads with hundreds of arguing comments, more directly I am asking :
- with this plugin (`@babel/plugin-proposal-decorators`) *can* you do decorators like `export default class Thing` at all? you could in the beta version, was this removed?
- if not, can you post a very very small snippet of a decorator that this plugin actually accepts so I understand 'code first' what should be written ?
- could this simply be a problem with babel-eslint @9 ? where it is indeed parsing, but somehow the linter is throwing anyways?

Thanks

**Comment by nicolo-ribaudo** [comment]
Sorry for the confusion, I get that old/new proposal doesn't mean anything for many people.

The "old" proposal is the one y'all are used to: it's the only one implemented in Babel and TypeScript. It's the one supported by `babel-plugin-transform-decorators-legacy` and `@babel/plugin-transform-decorators, { legacy: true }`. In `@babel/parser` it is `decorators-legacy`.

The "new" proposal is currently only implemented in `@babel/parser` (using the `decorators` plugin) and in `babel-eslint`, because it uses `@babel/parser`. We are implementing it (https://github.com/babel/babel/pull/7976), and also the TypeScript team is.

The `decoratorsBeforeExport` option is only meaningful for the "new" version of the proposal because, as you noted, there isn't consensus yet. You can't really use it in `@babel/plugin-proposal-decorators` because #7976 has not been merged yet, but you can use it in the `@babel/parser`'s `decorators` plugin.

---

> with this plugin (`@babel/plugin-proposal-decorators`) can you do decorators like export default class Thing at all? you could in the beta version, was this removed?

You still can, the old behavior hasn't changed. We only require the `legacy` option now:
```js
const out = babel.transformSync(
  `
  @decorator
  export default class Foo {}
  `,
  {
    plugins: [
      [
        require("./packages/babel-plugin-proposal-decorators"),
        { legacy: true },
      ],
    ],
  }
);

console.log(out.code);
```
logs
```js
var _class;

let Foo = decorator(_class = class Foo {}) || _class;

export { Foo as default };
```

> could this simply be a problem with babel-eslint @9 ? where it is indeed parsing, but somehow the linter is throwing anyways? (maybe there is non parity between the linter and parser?)

In babel-eslint [you have to opt-in](https://github.com/babel/babel-eslint/releases/tag/v9.0.0) to use the "old" proposal: in your eslint config, you should have something like this:
```json5
{
  parserOptions: {
    ecmaFeatures: {
      legacyDecorators: true
    }
  }
}
```

**Comment by jaydenseric** [comment]
This issue should not have been closed, since the docs are still incorrect:

<img width="882" alt="screen shot 2018-08-30 at 5 58 02 pm" src="https://user-images.githubusercontent.com/1754873/44837972-5bc08300-ac7e-11e8-98dc-293b5b60eef6.png">

The `decoratorsBeforeExport` does not default to `false`.

**Comment by nicolo-ribaudo** [comment]
Do you want to open a PR to babel/website?

**Comment by existentialism** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/56288/44862327-10877f80-ac40-11e8-9ca0-5be55be9bb69.png)

**Comment by damianobarbati** [comment]
@the-simian I had you same problem, solved with @nicolo-ribaudo suggestion, change you eslint config:
```
    "eslintConfig": {
        "parser": "babel-eslint",
        "parserOptions": {
            "ecmaVersion": 2019,
            "sourceType": "module",
            "impliedStrict": true,
            "ecmaFeatures": {
                "jsx": true,
                "impliedStrict": true,
                "globalReturn": false,
                "experimentalObjectRestSpread": true,
                "legacyDecorators": true
            }
        },
        "env": {
            "browser": true,
            "serviceworker": true,
            "node": true,
            "jest": true,
            "es6": true
        },
        "plugins": [
            "react",
            "jest"
        ],
        "extends": [
            "eslint:recommended",
            "plugin:react/recommended",
            "plugin:jest/recommended"
        ],
        "rules": {
            "no-console": "off"
        }
    },
```

**Comment by wyuenho** [comment]
The doc is not fixed. It still says `decoratorsBeforeExport` defaults to false.

<img width="1111" alt="screen shot 2018-09-09 at 12 59 09" src="https://user-images.githubusercontent.com/160028/45264171-32e37f00-b430-11e8-9830-bd781b2580e2.png">

**Comment by xtuc** [comment]
@wyuenho could you please open an issue on https://github.com/babel/website?

**Comment by jcabrerazuniga** [comment]
> Sorry for the confusion, I get that old/new proposal doesn't mean anything for many people.
> 
> The "old" proposal is the one y'all are used to: it's the only one implemented in Babel and TypeScript. It's the one supported by `babel-plugin-transform-decorators-legacy` and `@babel/plugin-transform-decorators, { legacy: true }`. In `@babel/parser` it is `decorators-legacy`.
> 
> The "new" proposal is currently only implemented in `@babel/parser` (using the `decorators` plugin) and in `babel-eslint`, because it uses `@babel/parser`. We are implementing it (#7976), and also the TypeScript team is.
> 
> The `decoratorsBeforeExport` option is only meaningful for the "new" version of the proposal because, as you noted, there isn't consensus yet. You can't really use it in `@babel/plugin-proposal-decorators` because #7976 has not been merged yet, but you can use it in the `@babel/parser`'s `decorators` plugin.
> 
> > with this plugin (`@babel/plugin-proposal-decorators`) can you do decorators like export default class Thing at all? you could in the beta version, was this removed?
> 
> You still can, the old behavior hasn't changed. We only require the `legacy` option now:
> 
> ```js
> const out = babel.transformSync(
>   `
>   @decorator
>   export default class Foo {}
>   `,
>   {
>     plugins: [
>       [
>         require("./packages/babel-plugin-proposal-decorators"),
>         { legacy: true },
>       ],
>     ],
>   }
> );
> 
> console.log(out.code);
> ```
> 
> logs
> 
> ```js
> var _class;
> 
> let Foo = decorator(_class = class Foo {}) || _class;
> 
> export { Foo as default };
> ```
> 
> > could this simply be a problem with babel-eslint @9 ? where it is indeed parsing, but somehow the linter is throwing anyways? (maybe there is non parity between the linter and parser?)
> 
> In babel-eslint [you have to opt-in](https://github.com/babel/babel-eslint/releases/tag/v9.0.0) to use the "old" proposal: in your eslint config, you should have something like this:
> 
> ```js
> {
>   parserOptions: {
>     ecmaFeatures: {
>       legacyDecorators: true
>     }
>   }
> }
> ```

How can you set the legacyDcorators:false  in webpack?

**Comment by novaterata** [comment]
Yes, please explain how to resolve this with a webpack config. I dont' even know where to start with this error.

**Comment by nicolo-ribaudo** [comment]
What is your current config?

**Comment by novaterata** [comment]
@nicolo-ribaudo This is my webpack 3.x config, which is used by electron-webpack. I'm taking over this project and I'm very ignorant of why things are configured the way they are.

.babelrc
```
{
  "presets": [
    "babel-preset-es2015-allow-top-level-this"
  ],
  "plugins": [
    "add-module-exports",
    "transform-remove-strict-mode"
  ]
}
```
webpack.config.js
```
// This configuration will be automatically merged with the electron-build default webpack configuration
// https://webpack.electron.build/modifying-webpack-configurations
const projectConfig = require('./project.config');
const webpack = require('webpack');
const isDev = process.env.NODE_ENV === "development";

module.exports = {
    module: {
        rules: [
            {
                test: /\.js$/,
                use: {
                    loader: 'babel-loader'
                }
            },
            {
                test: /\.jsx$/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ['react']
                    }
                }
            },
            {
                test: /\.css$/,
                use: [{
                    loader: "style-loader"
                }, {
                    loader: "css-loader"
                }]
            },
            {
                test: /\.less$/,
                use: [{
                    loader: "style-loader"
                }, {
                    loader: "css-loader"
                }, {
                    loader: "postcss-loader"
                }, {
                    loader: "less-loader"
                }]
            },
            {
                test: /\.WOFF$/,
                use: "url-loader?mimetype=application/font-woff"
            },
            {
                test: /\.json$/,
                use: "json-loader"
            },
            {
                test: /\.txt$/,
                use: 'raw-loader'
            },
            {
                test: /\.waveform/,
                use: 'arraybuffer-loader'
            }
        ]
    },
    devtool: isDev ? 'eval-source-map' : 'source-map',
    plugins: [
        new webpack.DefinePlugin({
            'process.env.NODE_ENV': isDev ? JSON.stringify('development') : JSON.stringify('production')
        }),
        new webpack.ProvidePlugin({
            _: 'underscore',
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery',
            Backbone: 'backbone',
            Bb: 'backbone',
            Marionette: 'backbone.marionette',
            Mn: 'backbone.marionette',
            d3: 'd3'
        })
    ],
    resolve: {
        modules: [
            projectConfig.srcDirectoryPath,
            projectConfig.nodeModulesDirectoryPath
        ],
        alias: {
            root: projectConfig.rootDirectoryPath,
            apps: projectConfig.appsDirectoryPath,
            data: projectConfig.dataDirectoryPath,
            svg: projectConfig.svgDirectoryPath,
            modules: projectConfig.nodeModulesDirectoryPath,
            'jquery-ui': projectConfig.jQueryUIDirectoryPath
        }
    }
};

```

And of course when attempting to upgrade to Webpack 4.x, I've changed the babel 6 versions of things to the babel 7 `@babel\preset-react` etc.  I've also told electron-webpack to not even use this config, just the default, and I still get the same decoratorsBeforeExport error. I'm not even using decorators.

Unfortunately I don't have my Webpack 4.x attempt because it's just too frustrating of an endeavor right now, so I had to revert and move on.

**Comment by nicolo-ribaudo** [comment]
You can run `npx nls why @babel/plugin-proposa-decorators` to see why it is installed.

**Comment by novaterata** [comment]
Thanks, that's very helpful

**Comment by Aszmel** [comment]
recently was getting problem with this error and installed
npm install --save-dev @babel/plugin-proposal-decorators
and setup 
`"babel": {
    "plugins": [
      [
        "@babel/plugin-proposal-decorators",
        {
          "legacy": true
        }
      ]
    ],
    "presets": [
      "react-app"
    ]
  },`

**Comment by sureshramola** [comment]
his run my code with some errors, but app was working, I'm a beginner, so hope this comment is

**Comment by sergiotapia** [comment]
For would be Googler's and create-react-app users.

Create your `create-react-app`.

Then eject the project:

```
yarn eject
```

Add mobx, mobx-react and the decorator plugin:

```
yarn add @babel/plugin-proposal-decorators mobx mobx-react
```

Then in your package.json you'll see:

```
"babel": {
  "presets": [
    "react-app"
  ]
}
```

Just update it to:

```
"babel": {
  "plugins": [
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ]
  ],
  "presets": [
    "react-app"
  ]
}
```

**Comment by hoenth** [comment]
@sergiotapia Did you mean 'Then in your .babelrc`
