### ISSUE TITLE
Exports is not defined.

### ISSUE THREAD

**Issue by shrinktofit** [babel/babel#9745]
## Bug Report

**Current Behavior**
babel/babel#9589 supports reporting error If the exported symbol is not defined. For multi-signatures function in TypeScript, the exported symbol is treated as undefined.

**Input Code**
```ts
// .ts:
function vec3(other?: vec3);
function vec3(x: number, y: number, z: number);
function vec3(x?: number | vec3, y: number, z: number) {
    /// xxxx
}
export { vec3 }; // Babel says that "export vec3 is not defined"
```

**Expected behavior/code**
No error.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
// A regular babel config using typescript-env
{
}
```

**Environment**

**Possible Solution**
My current solution is force use "@babel/core","@babel/parse" at "7.3.4" version.

**Comment by nicolo-ribaudo** [comment]
Do you also define the function body somewhere in that file?

**Comment by shrinktofit** [comment]
> Do you also define the function body somewhere in that file?

Yes. 

![image](https://user-images.githubusercontent.com/28807867/54811555-eb358e00-4cc3-11e9-953a-c326478524e8.png)
![image](https://user-images.githubusercontent.com/28807867/54811566-f12b6f00-4cc3-11e9-9e56-4b68161a8fc6.png)

**Comment by danez** [comment]
This should be fixed with version 7.4.2 of @babel/parser. Can you make sure you have the latests version and try again?

**Comment by nicolo-ribaudo** [comment]
Yeah, this throws when using v7.4.0 (and `strictMode` is false), but works with v7.4.2.
Fixed by #9725.

**Comment by shrinktofit** [comment]
@nicolo-ribaudo  I have upgrade `@babel/parser` to `7.4.2`, there's still the same error.

![image](https://user-images.githubusercontent.com/28807867/54974129-dd3a8280-4fcd-11e9-925c-7934318ce497.png)

![image](https://user-images.githubusercontent.com/28807867/54974139-ed526200-4fcd-11e9-83fc-8fd6d5a503ba.png)

My config(called by rollup):

```
babel({
            highlightCode: true,

            extensions: ['.js', '.ts'],

            presets: [
                [
                    '@babel/preset-env',
                    // { targets: { "esmodules": true } }
                ],
                '@babel/preset-typescript'
            ],

            plugins: [
                ['@babel/plugin-proposal-decorators', {
                    legacy: true
                }],
                ['@babel/plugin-proposal-class-properties', {
                    loose: true
                }],
            ],

            ignore: [
                'node_modules/**'
            ]
        })
```

**Comment by airato** [comment]
this should be fixed in v7.4.4
