### ISSUE TITLE
Export 'IValues' is not defined

### ISSUE THREAD

**Issue by emilgpa** [babel/babel#9895]
## Bug Report

**Current Behavior**

Export 'IValues' is not defined.

```
ERROR in ./ts/components/sections/ajustar_descuadre.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Front BPM\Cuadre\trunk\Cuadre\WebContent\ts\components\sections\ajustar_descuadre.tsx: Export 'IValues' is not defined (44:8)

  42 | }
  43 | 
> 44 | export {IValues as IAjustarDescuadreValues}
     |         ^
  45 | 
  46 | interface IBaseProps {
  47 |     importValue: string
    at Object.raise (C:\Front BPM\Cuadre\trunk\Cuadre\WebContent\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:3851:17)
    at Object.parseTopLevel (C:\Front BPM\Cuadre\trunk\Cuadre\WebContent\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:7226:14)
    at Object.parse (C:\Front BPM\Cuadre\trunk\Cuadre\WebContent\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:8863:17)
    at parse (C:\Front BPM\Cuadre\trunk\Cuadre\WebContent\node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:11135:38)
    at parser (C:\Front BPM\Cuadre\trunk\Cuadre\WebContent\node_modules\@babel\core\lib\transformation\normalize-file.js:170:34)
    at normalizeFile (C:\Front BPM\Cuadre\trunk\Cuadre\WebContent\node_modules\@babel\core\lib\transformation\normalize-file.js:138:11)
    at runSync (C:\Front BPM\Cuadre\trunk\Cuadre\WebContent\node_modules\@babel\core\lib\transformation\index.js:44:43)
    at runAsync (C:\Front BPM\Cuadre\trunk\Cuadre\WebContent\node_modules\@babel\core\lib\transformation\index.js:35:14)
    at process.nextTick (C:\Front BPM\Cuadre\trunk\Cuadre\WebContent\node_modules\@babel\core\lib\transform.js:34:34)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./ts/components/sections/detalle_descuadre_cerrado/detalle_descuadre_cerrado.tsx 56:48-81
 @ ./ts/components/index.ts
 @ ./ts/app.tsx
 @ ./ts/main.tsx
```

**Input Code**
- code wrriten in TypeScript and React. Nothing special.

**Expected behavior/code**
Should successfully transpile.

**Babel Configuration (.babelrc, package.json, cli command)**

```js
{
  "presets": [
    "@babel/react",
    "@babel/typescript",
    [
      "@babel/env",
      {
        "modules": false,
        "targets": {
          "ie": "11",
          "chrome": "58"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": true
      }
    ],
    "@babel/proposal-object-rest-spread",
    "@babel/plugin-transform-react-jsx",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-transform-runtime"
  ]
}
```

**Environment**
- Babel version(s): ev7.4.3
- Node/npm version: Node 8.9.4/npm 5.6.0
- OS: Windows 10
- Monorepo: yes
- How you are using Babel: `loader`

**Comment by nicolo-ribaudo** [comment]
Fixed by https://github.com/babel/babel/pull/9766, released in v7.4.4

**Comment by emilgpa** [comment]
@nicolo-ribaudo I recently update babel to 7.4.4 but I still have the same error.

```
ERROR in ./ts/components/_table/with_filter.tsx 21:9
Module parse failed: Export 'IContext' is not defined (21:9)
You may need an appropriate loader to handle this file type.
| import Table from './table';
| import Filter from './filter';
> export { IContext as IWithFilterContext };
| var TableFilter = (_dec = inject('uiStore', 'appStore', 'dataStore'), _dec(_class = observer(_class = (_temp = _class2 =
| /*#__PURE__*/
 @ ./ts/components/sections/lista_tareas/lista_tareas.tsx 23:0-61 1206:79-96
 @ ./ts/components/index.ts
 @ ./ts/app.tsx
 @ ./ts/main.tsx

```

**Comment by emilgpa** [comment]
@nicolo-ribaudo Maybe 7.4.4 version handles `export {example}` but not with `as` keyword like `export {example as example1}`??

**Comment by nicolo-ribaudo** [comment]
It should work :thinking:
What does `npx nls why @babel/parser` say?

**Comment by emilgpa** [comment]
@nicolo-ribaudo (the output is very long): https://hastebin.com/raw/howekupupa

**Comment by gnirob** [comment]
No help with updating 7.4.4, even though there is no `as` syntax.

**Comment by TheAifam5** [comment]
Please reopen this issue since is not fixed!
